insert into employees (EMPLOYEE_ID, 
                        FIRST_NAME, 
                        LAST_NAME, 
                        EMAIL, 
                        PHONE_NUMBER, 
                        HIRE_DATE, 
                        JOB_ID, 
                        SALARY, 
                        COMMISSION_PCT, 
                        MANAGER_ID, 
                        DEPARTMENT_ID)
values(
        208,
        'Shamim',
        'Sarker',
        'shamims',
        '01723795366',
        sysdate,
        'IT_PROG',
        55000,
        null,
        205,100
        );